# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69fef4026e03b603e115677c22bb2b5eef0c68060aa143e3e4c9d23ddfd7ddb02532a306903e6b8bb25f451b961b124614f5ef788a97d5f8d9ab7fad23dc5e35

test:
  secret_key_base: 8b16fe5f63ae641beea0fefee554a5309460516ee5f2709e7486a8ff26d027b49351e599c9add70d2f35fc3e2f2e6da8d8683ce602bfebcc22ef09ee42bec636

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
